workflows:
  android-workflow:
    name: Build APK Android Callbook
    environment:
      flutter: stable
    scripts:
      - name: Clean
        script: flutter clean
      - name: Get Packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
