name: callbook_poc
description: Aplikasi Callbook POC INDONESIA Offline
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png